export const LIST_REQUESTED = 'USERS/LIST_REQUESTED'
export const LIST_SUCCEEDED = 'USERS/LIST_SUCCEEDED'
export const LIST_FAILED = 'USERS/LIST_FAILED'

export const PREV_LIST_REQUESTED = 'USERS/PREV_LIST_REQUESTED'
export const PREV_LIST_SUCCEEDED = 'USERS/PREV_LIST_SUCCEEDED'
export const PREV_LIST_FAILED = 'USERS/PREV_LIST_FAILED'

export const NEXT_LIST_REQUESTED = 'USERS/NEXT_LIST_REQUESTED'
export const NEXT_LIST_SUCCEEDED = 'USERS/NEXT_LIST_SUCCEEDED'
export const NEXT_LIST_FAILED = 'USERS/NEXT_LIST_FAILED'

export const GET_USER_BY_ID_REQUESTED = 'USERS/GET_USER_BY_ID_REQUESTED'
export const GET_USER_BY_ID_SUCCEEDED = 'USERS/GET_USER_BY_ID_SUCCEEDED'
export const GET_USER_BY_ID_FAILED = 'USERS/GET_USER_BY_ID_FAILED'
