export const LIST_REQUESTED = 'MAIN/LIST_REQUESTED'
export const LIST_SUCCEEDED = 'MAIN/LIST_SUCCEEDED'
export const LIST_FAILED = 'MAIN/LIST_FAILED'

export const ADD_REQUESTED = 'MAIN/ADD_REQUESTED'
export const ADD_SUCCEEDED = 'MAIN/ADD_SUCCEEDED'
export const ADD_FAILED = 'MAIN/ADD_FAILED'

export const REMOVE_REQUESTED = 'MAIN/REMOVE_REQUESTED'
export const REMOVE_SUCCEEDED = 'MAIN/REMOVE_SUCCEEDED'
export const REMOVE_FAILED = 'MAIN/REMOVE_FAILED'
